'use strict';

const test = require('node:test');
const assert = require('node:assert');
const path = require('path');

const { tmNebQ5, tmForPrimer } = require('../../src/tm');

// Generated by running the reference nearest-neighbour implementation over
// synthetic sequences. Regenerate with the snippet in test/README.md if that
// function ever changes.
const oracle = require(path.join(__dirname, '..', 'fixtures', 'tm-oracle.json'));

test('matches the reference Python implementation', () => {
  for (const { seq, tm } of oracle) {
    const got = tmNebQ5(seq);
    assert.notStrictEqual(got, null, `returned null for ${seq}`);
    assert.ok(
      Math.abs(got - tm) < 1e-9,
      `${seq}: expected ${tm}, got ${got} (delta ${Math.abs(got - tm)})`
    );
  }
});

test('is case insensitive and tolerates surrounding whitespace', () => {
  assert.strictEqual(tmNebQ5('atgcatgcatgc'), tmNebQ5('ATGCATGCATGC'));
  assert.strictEqual(tmNebQ5('  ATGCATGCATGC \n'), tmNebQ5('ATGCATGCATGC'));
});

test('returns null rather than throwing on unusable input', () => {
  // The Python raises ValueError here. In the extension that would abort a
  // cart add, so these degrade to a blank Tm instead.
  for (const bad of ['', 'A', 'ATGN', 'ATGCRYKM', 'ATG C', null, undefined, 42]) {
    assert.strictEqual(tmNebQ5(bad), null, `expected null for ${JSON.stringify(bad)}`);
  }
});

test('tmForPrimer prefers a /Tm qualifier from the file', () => {
  const withNote = tmForPrimer('ATGCATGCATGCATGC', { Tm: [60] });
  assert.deepStrictEqual(withNote, { tm: 60, tmSource: 'notes' });

  const computed = tmForPrimer('ATGCATGCATGCATGC', {});
  assert.strictEqual(computed.tmSource, 'computed');
  assert.ok(Number.isFinite(computed.tm));

  // A /Tm that is not a number must fall through to the calculation.
  const junk = tmForPrimer('ATGCATGCATGCATGC', { Tm: ['n/a'] });
  assert.strictEqual(junk.tmSource, 'computed');

  const degenerate = tmForPrimer('NNNN', {});
  assert.deepStrictEqual(degenerate, { tm: null, tmSource: null });
});
